default:
  image:
    name: bitnami/kubectl:1.22
    entrypoint: [""]

stages:
  - cmd

.import:
  stage: cmd
  script:
    - echo "Running car import in $ENV_NAME env ($NAMESPACE namespace)!"
    - export POD_NAME=$(kubectl -n ${NAMESPACE} get pod --selector app.kubernetes.io/name=x15-platform -o=name | head -1)
    - echo "Detected pod name ${POD_NAME}!"
    - echo "Running bin/console app:configurator:import $REGION $COUNTRY_CODE $DISTRIBUTION $IMPORT_COMMAND"
    - kubectl -n ${NAMESPACE} exec ${POD_NAME} -- bin/console app:configurator:import $REGION $COUNTRY_CODE $DISTRIBUTION $IMPORT_COMMAND

dev-import:
  extends: .import
  variables:
    NAMESPACE: dev
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: never
    - if: $ENV_NAME != "dev"
      when: never
    - if: $NAMESPACE && $REGION && $COUNTRY_CODE && $DISTRIBUTION && $IMPORT_COMMAND
  tags:
    - dev

dev-hk-import:
  extends: .import
  variables:
    NAMESPACE: dev-hk
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: never
    - if: $ENV_NAME != "dev-hk"
      when: never
    - if: $NAMESPACE && $REGION && $COUNTRY_CODE && $DISTRIBUTION && $IMPORT_COMMAND
  tags:
    - dev

sit-import:
  extends: .import
  variables:
    NAMESPACE: sit
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: never
    - if: $ENV_NAME != "sit"
      when: never
    - if: $NAMESPACE && $REGION && $COUNTRY_CODE && $DISTRIBUTION && $IMPORT_COMMAND
  tags:
    - sit

sit-hk-import:
  extends: .import
  variables:
    NAMESPACE: sit-hk
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: never
    - if: $ENV_NAME != "sit-hk"
      when: never
    - if: $NAMESPACE && $REGION && $COUNTRY_CODE && $DISTRIBUTION && $IMPORT_COMMAND
  tags:
    - sit

uat-import:
  extends: .import
  variables:
    NAMESPACE: uat
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: never
    - if: $ENV_NAME != "uat"
      when: never
    - if: $NAMESPACE && $REGION && $COUNTRY_CODE && $DISTRIBUTION && $IMPORT_COMMAND
  tags:
    - uat

uat-hk-import:
  extends: .import
  variables:
    NAMESPACE: uat-hk
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: never
    - if: $ENV_NAME != "uat-hk"
      when: never
    - if: $NAMESPACE && $REGION && $COUNTRY_CODE && $DISTRIBUTION && $IMPORT_COMMAND
  tags:
    - uat
